version: "3"

services: 
    database:
        image: mysql:5.6
        volumes:
            - tp_priou_db
        environment:
          MYSQL_ROOT_PASSWORD: myrootpassword
          MYSQL_DATABASE: tp_priou
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
            - 3356:3306
        networks: 
            - tp_priou
    pma:
        image: phpmyadmin/phpmyadmin:4.9
        ports:
            - 8090:80
        networks: 
            - tp_priou
        environment:
            PMA_HOST: database
            PMA_USER: test
            PMA_PASSWORD: test
    api:
        build: .
        container_name: testapi
        volumes: 
            - .:/usr/local/nginx/html
        ports:
            - 3050:3000 
        environment:
            DB_HOST: database
            DB_USER: 'test'
            DB_PASSWORD: 'test'
            DB_NAME: 'tp_priou'
        networks: 
            - tp_priou
networks:
    tp_priou:
volumes:
    tp_priou_db: