version: "3"

services:

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: tp_priou
      MYSQL_USER: hetic
      MYSQL_PASSWORD: +Hetic2019+
    ports:
      - 3350:3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - tp_database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8080:80
    networks:
      - tp_database
    environment:
      PMA_HOST: database
      PMA_USER: hetic
      PMA_PASSWORD: +Hetic2019+

  web:
    build: /home/hetic/API/server
    container_name: tp_priou
    volumes:
      - ./server:/var/www/html/public
    ports:
      - 8090:80
    environment:
      DB_HOST: database
      DB_USER: 'hetic'
      DB_PASSWORD: '+Hetic2019+'
      DB_NAME: 'tp_priou'
    networks:
      - tp_database

networks:
  tp_database:

  